#!/usr/bin/env python3
"""Generate Unicode simple case-mapping tables into crates/residc/resid_rt.c.

Extracts every codepoint whose simple lowercase/uppercase mapping (per
Python's unicodedata, which mirrors UnicodeData.txt) is a single differing
codepoint, and writes two sorted uint32 pair tables between
BEGIN/END CASE TABLES markers in resid_rt.c. `resid_case_simple` binary-
searches them after the algorithmic ranges. Multi-character SpecialCasing
expansions (e.g. ß → SS) are intentionally out of scope: the language maps
simple case only (spec §14.3).

Run from the repo root:  python3 tools/gen_case_tables.py
"""
import sys
import unicodedata

RT = "crates/residc/resid_rt.c"
BEGIN = "// BEGIN CASE TABLES — generated by tools/gen_case_tables.py; do not edit"
END = "// END CASE TABLES"


def simple_maps():
    """(upper_to_lower, lower_to_upper) sorted lists of (from, to)."""
    lower, upper = [], []
    for cp in range(0x110000):
        ch = chr(cp)
        lo = ch.lower()
        up = ch.upper()
        # Single-codepoint simple mapping only; multi-character
        # SpecialCasing expansions are out of scope (spec §14.3).
        if len(lo) == 1 and lo != ch:
            lower.append((cp, ord(lo)))
        if len(up) == 1 and up != ch:
            upper.append((cp, ord(up)))
    return lower, upper


def emit(rows, name):
    out = [f"static const uint32_t {name}[] = {{"]
    for i in range(0, len(rows), 4):
        chunk = ", ".join(f"0x{a:04X},0x{b:04X}" for a, b in rows[i : i + 4])
        out.append(f"    {chunk},")
    out.append("};")
    out.append(f"#define {name}_N {len(rows)}  /* pairs */")
    return "\n".join(out)


def main():
    lower, upper = simple_maps()
    with open(RT) as f:
        src = f.read()
    bi = src.index(BEGIN)
    ei = src.index(END) + len(END)
    block = (
        f"{BEGIN}\n"
        f"/* lower: {len(lower)} pairs, upper: {len(upper)} pairs. */\n"
        f"{emit(lower, 'CASE_TO_LOWER')}\n\n"
        f"{emit(upper, 'CASE_TO_UPPER')}\n"
        f"{END}"
    )
    open(RT, "w").write(src[:bi] + block + src[ei:])
    print(f"wrote {RT}: {len(lower)} lower pairs, {len(upper)} upper pairs")


if __name__ == "__main__":
    sys.exit(main())
