#!/usr/bin/env python3
"""Generate Unicode case-mapping tables into crates/residc/resid_rt.c.

Extracts every codepoint whose simple lowercase/uppercase mapping (per
Python's unicodedata, which mirrors UnicodeData.txt) is a single differing
codepoint, and writes two sorted uint32 pair tables between
BEGIN/END CASE TABLES markers in resid_rt.c. `resid_case_simple` binary-
searches them after the algorithmic ranges.

Also emits SPECIAL_UPPER: the unconditional multi-character uppercase
expansions from Unicode SpecialCasing.txt (ß→SS, ligatures, ŉ→ʼN, the
Greek ypogegrammeni forms, ...), consulted before the simple table.
Conditional rules handled directly in the runtime: Final_Sigma (Σ→ς
word-finally) in str_to_lower.

Run from the repo root:  python3 tools/gen_case_tables.py
"""
import sys
import unicodedata

RT = "crates/residc/resid_rt.c"
BEGIN = "// BEGIN CASE TABLES — generated by tools/gen_case_tables.py; do not edit"
END = "// END CASE TABLES"

# Unconditional SpecialCasing uppercase expansions (Unicode SpecialCasing.txt,
# locale-independent entries). Sorted by source codepoint.
SPECIAL_UPPER = {
    0x00DF: "SS",      # ß
    0x0149: "\u02BCN", # ŉ
    0x01F0: "J\u030C", # ǰ
    0x0390: "\u0399\u0308\u0301",  # ΐ
    0x03B0: "\u03A5\u0308\u0301",  # ΰ
    0x1E96: "H\u0331",
    0x1E97: "T\u0308",
    0x1E98: "W\u030A",
    0x1E99: "Y\u030A",
    0x1E9A: "A\u02BE",
    0x1F80: "\u1F08\u0399", 0x1F81: "\u1F09\u0399", 0x1F82: "\u1F0A\u0399",
    0x1F83: "\u1F0B\u0399", 0x1F84: "\u1F0C\u0399", 0x1F85: "\u1F0D\u0399",
    0x1F86: "\u1F0E\u0399", 0x1F87: "\u1F0F\u0399",
    0x1F88: "\u1F08\u0399", 0x1F89: "\u1F09\u0399", 0x1F8A: "\u1F0A\u0399",
    0x1F8B: "\u1F0B\u0399", 0x1F8C: "\u1F0C\u0399", 0x1F8D: "\u1F0D\u0399",
    0x1F8E: "\u1F0E\u0399", 0x1F8F: "\u1F0F\u0399",
    0x1F90: "\u1F98\u0399", 0x1F91: "\u1F99\u0399", 0x1F92: "\u1F9A\u0399",
    0x1F93: "\u1F9B\u0399", 0x1F94: "\u1F9C\u0399", 0x1F95: "\u1F9D\u0399",
    0x1F96: "\u1F9E\u0399", 0x1F97: "\u1F9F\u0399",
    0x1F98: "\u1F98\u0399", 0x1F99: "\u1F99\u0399", 0x1F9A: "\u1F9A\u0399",
    0x1F9B: "\u1F9B\u0399", 0x1F9C: "\u1F9C\u0399", 0x1F9D: "\u1F9D\u0399",
    0x1F9E: "\u1F9E\u0399", 0x1F9F: "\u1F9F\u0399",
    0x1FA0: "\u1FA8\u0399", 0x1FA1: "\u1FA9\u0399", 0x1FA2: "\u1FAA\u0399",
    0x1FA3: "\u1FAB\u0399", 0x1FA4: "\u1FAC\u0399", 0x1FA5: "\u1FAD\u0399",
    0x1FA6: "\u1FAE\u0399", 0x1FA7: "\u1FAF\u0399",
    0x1FA8: "\u1FA8\u0399", 0x1FA9: "\u1FA9\u0399", 0x1FAA: "\u1FAA\u0399",
    0x1FAB: "\u1FAB\u0399", 0x1FAC: "\u1FAC\u0399", 0x1FAD: "\u1FAD\u0399",
    0x1FAE: "\u1FAE\u0399", 0x1FAF: "\u1FAF\u0399",
    0x1FB2: "\u1FBA\u0345", 0x1FB3: "\u0391\u0345", 0x1FB4: "\u0386\u0345",
    0x1FB6: "\u0391\u0342",
    0x1FB7: "\u0391\u0342\u0345",
    0x1FBC: "\u0391\u0399",
    0x1FC2: "\u1FCA\u0345", 0x1FC3: "\u0397\u0345", 0x1FC4: "\u0389\u0345",
    0x1FC6: "\u0397\u0342",
    0x1FC7: "\u0397\u0342\u0345",
    0x1FCC: "\u0397\u0399",
    0x1FF2: "\u1FFA\u0345", 0x1FF3: "\u03A9\u0345", 0x1FF4: "\u038F\u0345",
    0x1FF6: "\u03A9\u0342",
    0x1FF7: "\u03A9\u0342\u0345",
    0x1FFC: "\u03A9\u0399",
    0xFB00: "FF", 0xFB01: "FI", 0xFB02: "FL", 0xFB03: "FFI", 0xFB04: "FFL",
    0xFB05: "ST", 0xFB06: "ST",
}


def simple_maps():
    """(upper_to_lower, lower_to_upper) sorted lists of (from, to)."""
    lower, upper = [], []
    for cp in range(0x110000):
        ch = chr(cp)
        lo = ch.lower()
        up = ch.upper()
        # Single-codepoint simple mapping only; multi-character
        # expansions live in SPECIAL_UPPER.
        if len(lo) == 1 and lo != ch:
            lower.append((cp, ord(lo)))
        if len(up) == 1 and up != ch:
            upper.append((cp, ord(up)))
    return lower, upper


def emit(rows, name):
    out = [f"static const uint32_t {name}[] = {{"]
    for i in range(0, len(rows), 4):
        chunk = ", ".join(f"0x{a:04X},0x{b:04X}" for a, b in rows[i : i + 4])
        out.append(f"    {chunk},")
    out.append("};")
    out.append(f"#define {name}_N {len(rows)}  /* pairs */")
    return "\n".join(out)


def emit_special():
    rows = sorted(SPECIAL_UPPER.items())
    out = ["static const struct { uint32_t cp; const char* up; } SPECIAL_UPPER[] = {"]
    for cp, s in rows:
        lit = "".join(f"\\x{b:02X}" for b in s.encode("utf-8"))
        # Escape sequences must not swallow a following hex digit.
        lit = lit.replace("\\x", "\\x")  # keep readable; C concats adjacent
        parts = []
        for i in range(0, len(lit), 4):
            parts.append(lit[i : i + 4])
        c_lit = '"' + '""'.join(parts) + '"'
        out.append(f"    {{0x{cp:04X}, {c_lit}}},")
    out.append("};")
    out.append(f"#define SPECIAL_UPPER_N {len(rows)}")
    return "\n".join(out)


def main():
    lower, upper = simple_maps()
    with open(RT) as f:
        src = f.read()
    bi = src.index(BEGIN)
    ei = src.index(END) + len(END)
    block = (
        f"{BEGIN}\n"
        f"/* lower: {len(lower)} pairs, upper: {len(upper)} pairs, "
        f"special-upper: {len(SPECIAL_UPPER)} expansions. */\n"
        f"{emit(lower, 'CASE_TO_LOWER')}\n\n"
        f"{emit(upper, 'CASE_TO_UPPER')}\n\n"
        f"{emit_special()}\n"
        f"{END}"
    )
    open(RT, "w").write(src[:bi] + block + src[ei:])
    print(
        f"wrote {RT}: {len(lower)} lower pairs, {len(upper)} upper pairs, "
        f"{len(SPECIAL_UPPER)} special-upper expansions"
    )


if __name__ == "__main__":
    sys.exit(main())
