#!/usr/bin/env python3
"""Generate lib/p256.resid and lib/p384.resid from one template.

Both curves share every line of their arithmetic; only the width, the
prime, the order and the constants differ. Edit the template here and
rerun (python3 tools/gen_nistp.py); never edit the generated files.

Design (see the header written into each file):
  - field and scalar elements are native UInt(W) integers in Montgomery
    form, with R = 2^K and W wide enough that t + q*m never overflows;
  - the curve code is written once, generic over a per-curve behavior
    (P256Word(F, B), P384Word(F, B)) with a public instance (UInt(W), Int)
    and a secret one (Secret(UInt(W)), Secret(UInt(8))), so the compiler
    checks the copy that computes on private keys and nonces (spec §48);
    what is published (signatures, public keys, validity verdicts) goes
    through the open verb, a declassification at secret types;
  - every operation on a secret is branch-free (masks, no comparisons,
    no data-dependent indexing) and uses wrapping_u* so no overflow check
    branches on a secret either;
  - points use the complete projective formulas of Renes, Costello and
    Batina (2016, algorithms 4 and 6, a = -3), so infinity and doubling
    need no special case, and scalar multiplication is a fixed-length
    double-and-add-always with a masked select.
"""
import os
import re

CURVES = {
    "p256": dict(
        K=256, W=576, T="P256Pt", A="P256Aff", S="P256Sig", BW="P256Word", XY="P256Xy",
        p=2**256 - 2**224 + 2**192 + 2**96 - 1,
        n=0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551,
        b=0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b,
        gx=0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296,
        gy=0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5,
        name="NIST P-256 (secp256r1)",
    ),
    "p384": dict(
        K=384, W=832, T="P384Pt", A="P384Aff", S="P384Sig", BW="P384Word", XY="P384Xy",
        p=2**384 - 2**128 - 2**96 + 2**32 - 1,
        n=0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973,
        b=0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef,
        gx=0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7,
        gy=0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f,
        name="NIST P-384 (secp384r1)",
    ),
}

TEMPLATE = r'''// lib/@X@.resid — @NAME@: ECDSA (verify, sign with an RFC 6979
// deterministic nonce), ECDH and point decoding, in pure Resid.
//
// GENERATED by tools/gen_nistp.py from the template shared with the other
// NIST curve; edit the generator, not this file.
//
// One implementation for public and secret data (spec §48). The field,
// scalar and point arithmetic, the ladder, key derivation, ECDH, signing
// and the RFC 6979 nonce are written once, generic over @BW@(F, B):
// F is a field element (UInt(@W@), or Secret(UInt(@W@)) when it derives
// from a private key or a nonce) and B a byte (Int, or Secret(UInt(8))).
// The secret copy is checked by the compiler: no branch, index,
// comparison or division depends on a private key, a nonce or an ECDH
// result. The public copy is the same code; verification and point
// decoding use only it.
//
// Field and scalar elements are in Montgomery form (R = 2^@K@). @W@ bits
// leave room for t + q*m, so nothing wraps. Selects are masks (through
// ct_hide), reductions subtract with a borrow bit, the scalar ladder runs
// all @K@ steps, and arithmetic wraps, so no overflow check branches on a
// value either. What becomes public goes through @X@w_open: a signature,
// a public key, and the verdicts "this scalar is usable" and "this point
// is not infinity". At secret types that is a declassification, so the
// secret copies of signing, key derivation and ECDH need
// @requires(declassify); the ECDH result itself stays secret.
//
// Points are projective (X:Y:Z) with the complete formulas of Renes,
// Costello and Batina (2016, algorithms 4 and 6 for a = -3): one formula
// covers doubling and the point at infinity (Z = 0), so there is no
// special case to branch on.

import "hash.resid";
import "word.resid";
import "sha256g.resid";
import "sha512g.resid";

// ─── Constants ───────────────────────────────────────────────────────

pub Int @X@_bytes() { return @KB@; }
pub UInt(@W@) @X@_p() { return @P@; }
pub UInt(@W@) @X@_n() { return @N@; }
pub UInt(@W@) @X@_gx() { return @GX@; }
pub UInt(@W@) @X@_gy() { return @GY@; }
// -p^-1 and -n^-1 mod R
UInt(@W@) @X@_pinv() { return @PINV@; }
UInt(@W@) @X@_ninv() { return @NINV@; }
// R^2 mod p and R^2 mod n, to enter the Montgomery domain
UInt(@W@) @X@_rrp() { return @RRP@; }
UInt(@W@) @X@_rrn() { return @RRN@; }
// R mod p (one), b and G, all in Montgomery form
UInt(@W@) @X@_one() { return @ONEM@; }
UInt(@W@) @X@_bm() { return @BM@; }
UInt(@W@) @X@_gxm() { return @GXM@; }
UInt(@W@) @X@_gym() { return @GYM@; }
// p - 2, n - 2 (inversion) and (p + 1) / 4 (square root; p = 3 mod 4)
UInt(@W@) @X@_pm2() { return @PM2@; }
UInt(@W@) @X@_nm2() { return @NM2@; }
UInt(@W@) @X@_psq() { return @PSQ@; }
// R - 1, the guard bit 2^(K+8) and the mask below it, all ones
UInt(@W@) @X@_rmask() { return @RMASK@; }
UInt(@W@) @X@_guard() { return @GUARD@; }
UInt(@W@) @X@_gmask() { return @GMASK@; }
UInt(@W@) @X@_ones() { return @ONES@; }
UInt(@W@) @X@_zero() { return 0; }

// ─── Field words: public and secret ─────────────────────────────────
// @BW@(F, B): the @W@-bit operations the curve code needs. Arithmetic
// wraps modulo 2^@W@; shift amounts and lifted constants are public.

behavior @BW@(F, B) {
    F @X@w_add(F a, F b);
    F @X@w_sub(F a, F b);
    F @X@w_mul(F a, F b);
    F @X@w_and(F a, F b);
    F @X@w_or(F a, F b);
    F @X@w_xor(F a, F b);
    F @X@w_shr(F x, Int n);
    F @X@w_shl(F x, Int n);
    F @X@w_mask(F bit);              // all ones when bit's low bit is 1, else 0
    F @X@w_lift(UInt(@W@) k);        // a public value taking part
    F @X@w_from_byte(B b);           // a byte (0..255)
    B @X@w_byte(F x, Int sh);        // the byte at bit sh
    UInt(@W@) @X@w_open(F x);        // publish (a declassification at secret types)
}

UInt(@W@) @X@i_add(UInt(@W@) a, UInt(@W@) b) { return wrapping_uadd(a, b); }
UInt(@W@) @X@i_sub(UInt(@W@) a, UInt(@W@) b) { return wrapping_usub(a, b); }
UInt(@W@) @X@i_mul(UInt(@W@) a, UInt(@W@) b) { return wrapping_umul(a, b); }
UInt(@W@) @X@i_and(UInt(@W@) a, UInt(@W@) b) { return a & b; }
UInt(@W@) @X@i_or(UInt(@W@) a, UInt(@W@) b) { return a | b; }
UInt(@W@) @X@i_xor(UInt(@W@) a, UInt(@W@) b) { return a ^ b; }
UInt(@W@) @X@i_shr(UInt(@W@) x, Int n) { return x >> (UInt(@W@)) n; }
UInt(@W@) @X@i_shl(UInt(@W@) x, Int n) { return x << (UInt(@W@)) n; }
// The bit passes through ct_hide so the optimizer cannot turn the mask
// back into a branch.
UInt(@W@) @X@i_mask(UInt(@W@) bit) {
    Int h = ct_hide(wrapping_i64(bit & 1));
    return wrapping_usub(@X@_zero(), (UInt(@W@)) wrapping_u64(h));
}
UInt(@W@) @X@i_lift(UInt(@W@) k) { return k; }
UInt(@W@) @X@i_from_byte(Int b) { return (UInt(@W@)) wrapping_u64(b & 255); }
Int @X@i_byte(UInt(@W@) x, Int sh) { return wrapping_i64((x >> (UInt(@W@)) sh) & 255); }
// ct_public: a value computed from a secret marked for tests/ct is public
// from here on.
UInt(@W@) @X@i_open(UInt(@W@) x) { return ct_public(x); }

@BW@(UInt(@W@), Int) = { .@X@w_add = @X@i_add, .@X@w_sub = @X@i_sub, .@X@w_mul = @X@i_mul, .@X@w_and = @X@i_and, .@X@w_or = @X@i_or, .@X@w_xor = @X@i_xor, .@X@w_shr = @X@i_shr, .@X@w_shl = @X@i_shl, .@X@w_mask = @X@i_mask, .@X@w_lift = @X@i_lift, .@X@w_from_byte = @X@i_from_byte, .@X@w_byte = @X@i_byte, .@X@w_open = @X@i_open };

Secret(UInt(@W@)) @X@s_add(Secret(UInt(@W@)) a, Secret(UInt(@W@)) b) { return wrapping_uadd(a, b); }
Secret(UInt(@W@)) @X@s_sub(Secret(UInt(@W@)) a, Secret(UInt(@W@)) b) { return wrapping_usub(a, b); }
Secret(UInt(@W@)) @X@s_mul(Secret(UInt(@W@)) a, Secret(UInt(@W@)) b) { return wrapping_umul(a, b); }
Secret(UInt(@W@)) @X@s_and(Secret(UInt(@W@)) a, Secret(UInt(@W@)) b) { return a & b; }
Secret(UInt(@W@)) @X@s_or(Secret(UInt(@W@)) a, Secret(UInt(@W@)) b) { return a | b; }
Secret(UInt(@W@)) @X@s_xor(Secret(UInt(@W@)) a, Secret(UInt(@W@)) b) { return a ^ b; }
Secret(UInt(@W@)) @X@s_shr(Secret(UInt(@W@)) x, Int n) { return x >> (UInt(@W@)) n; }
Secret(UInt(@W@)) @X@s_shl(Secret(UInt(@W@)) x, Int n) { return x << (UInt(@W@)) n; }
Secret(UInt(@W@)) @X@s_mask(Secret(UInt(@W@)) bit) {
    Secret(Int) h = ct_hide(wrapping_i64(bit & 1));
    return wrapping_usub(@X@_zero(), (UInt(@W@)) wrapping_u64(h));
}
Secret(UInt(@W@)) @X@s_lift(UInt(@W@) k) { return classify(k); }
Secret(UInt(@W@)) @X@s_from_byte(Secret(UInt(8)) b) { return (UInt(@W@)) b; }
Secret(UInt(8)) @X@s_byte(Secret(UInt(@W@)) x, Int sh) { return wrapping_u8(x >> (UInt(@W@)) sh); }
@requires(declassify)
UInt(@W@) @X@s_open(Secret(UInt(@W@)) x) { return ct_public(declassify(x, "@NAME@ signature, public key or validity verdict")); }

@BW@(Secret(UInt(@W@)), Secret(UInt(8))) = { .@X@w_add = @X@s_add, .@X@w_sub = @X@s_sub, .@X@w_mul = @X@s_mul, .@X@w_and = @X@s_and, .@X@w_or = @X@s_or, .@X@w_xor = @X@s_xor, .@X@w_shr = @X@s_shr, .@X@w_shl = @X@s_shl, .@X@w_mask = @X@s_mask, .@X@w_lift = @X@s_lift, .@X@w_from_byte = @X@s_from_byte, .@X@w_byte = @X@s_byte, .@X@w_open = @X@s_open };

// ─── Branch-free helpers ─────────────────────────────────────────────

// 1 when v != 0, else 0 (v < 2^(@W@-1)): 0 - v has its top bit set
// exactly when v is nonzero.
@needs(@BW@(F, B))
pub F @X@_nonzero(F v) {
    F z = @X@w_lift(@X@_zero());
    F one = @X@w_lift(1);
    return @X@w_and(@X@w_shr(@X@w_or(v, @X@w_sub(z, v)), @WM1@), one);
}

// u - m when u >= m, else u, for u < 2m (m public).
@needs(@BW@(F, B))
F @X@_csub(F u, UInt(@W@) m) {
    F guard = @X@w_lift(@X@_guard());
    F mm = @X@w_lift(m);
    F gmask = @X@w_lift(@X@_gmask());
    F ones = @X@w_lift(@X@_ones());
    F d = @X@w_sub(@X@w_add(u, guard), mm);
    F keep = @X@w_mask(@X@w_shr(d, @K8@));
    return @X@w_or(@X@w_and(@X@w_and(d, gmask), keep), @X@w_and(u, @X@w_xor(keep, ones)));
}

// a * b / R mod m (Montgomery), a, b < m.
@needs(@BW@(F, B))
F @X@_mont(F a, F b, UInt(@W@) m, UInt(@W@) minv) {
    F rm = @X@w_lift(@X@_rmask());
    F mi = @X@w_lift(minv);
    F mm = @X@w_lift(m);
    F t = @X@w_mul(a, b);
    F q = @X@w_and(@X@w_mul(@X@w_and(t, rm), mi), rm);
    return @X@_csub(@X@w_shr(@X@w_add(t, @X@w_mul(q, mm)), @K@), m);
}

// ─── Field (mod p), Montgomery form ──────────────────────────────────

@needs(@BW@(F, B))
pub F @X@_fmul(F a, F b) { return @X@_mont(a, b, @X@_p(), @X@_pinv()); }
@needs(@BW@(F, B))
pub F @X@_fsq(F a) { return @X@_mont(a, a, @X@_p(), @X@_pinv()); }
@needs(@BW@(F, B))
pub F @X@_fadd(F a, F b) { return @X@_csub(@X@w_add(a, b), @X@_p()); }
@needs(@BW@(F, B))
pub F @X@_fsub(F a, F b) {
    F p = @X@w_lift(@X@_p());
    return @X@_csub(@X@w_sub(@X@w_add(a, p), b), @X@_p());
}
@needs(@BW@(F, B))
pub F @X@_fto(F a) {
    F rr = @X@w_lift(@X@_rrp());
    return @X@_fmul(a, rr);
}
@needs(@BW@(F, B))
pub F @X@_ffrom(F a) {
    F one = @X@w_lift(1);
    return @X@_fmul(a, one);
}

// a^e for a public exponent e, MSB first from bit i: which steps multiply
// depends on e only.
@needs(@BW@(F, B))
F @X@_fpow(F a, UInt(@W@) e, Int i, F acc) {
    if (i < 0) { return acc; }
    F s = @X@_fsq(acc);
    UInt(@W@) sh = (UInt(@W@)) i;
    F r = if (((e >> sh) & 1) == 1) { @X@_fmul(s, a) } else { s };
    return @X@_fpow(a, e, i - 1, r);
}

// 1/a (Fermat, a fixed public exponent); 0 maps to 0.
@needs(@BW@(F, B))
pub F @X@_finv(F a) {
    F one = @X@w_lift(@X@_one());
    return @X@_fpow(a, @X@_pm2(), @KM1@, one);
}

// A square root of a when one exists (check by squaring).
@needs(@BW@(F, B))
pub F @X@_fsqrt(F a) {
    F one = @X@w_lift(@X@_one());
    return @X@_fpow(a, @X@_psq(), @KM1@, one);
}

// ─── Scalars (mod n), Montgomery form ────────────────────────────────

@needs(@BW@(F, B))
pub F @X@_smul(F a, F b) { return @X@_mont(a, b, @X@_n(), @X@_ninv()); }
@needs(@BW@(F, B))
pub F @X@_sadd(F a, F b) { return @X@_csub(@X@w_add(a, b), @X@_n()); }
@needs(@BW@(F, B))
pub F @X@_sto(F a) {
    F rr = @X@w_lift(@X@_rrn());
    return @X@_smul(a, rr);
}
@needs(@BW@(F, B))
pub F @X@_sfrom(F a) {
    F one = @X@w_lift(1);
    return @X@_smul(a, one);
}

@needs(@BW@(F, B))
F @X@_spow(F a, UInt(@W@) e, Int i, F acc) {
    if (i < 0) { return acc; }
    F s = @X@_smul(acc, acc);
    UInt(@W@) sh = (UInt(@W@)) i;
    F r = if (((e >> sh) & 1) == 1) { @X@_smul(s, a) } else { s };
    return @X@_spow(a, e, i - 1, r);
}

// 1/a mod n, both in Montgomery form (Fermat: a^(n-2), a fixed public
// exponent, so the nonce's inverse takes the same steps for every nonce).
@needs(@BW@(F, B))
pub F @X@_sinv(F a) {
    F one = @X@w_lift(1);
    return @X@_spow(a, @X@_nm2(), @KM1@, @X@_sto(one));
}

// A value below 2^@K@ reduced mod n (2^@K@ < 2n).
@needs(@BW@(F, B))
pub F @X@_reduce_n(F v) { return @X@_csub(v, @X@_n()); }

// ─── Points ──────────────────────────────────────────────────────────

// Projective, Montgomery-form coordinates; Z = 0 is infinity.
pub type @T@(F) = { F x; F y; F z; };

// Affine, ordinary integers, public; ok is false for infinity or a bad
// encoding.
pub type @A@ = { UInt(@W@) x; UInt(@W@) y; Bool ok; };

// Affine at F; ok (whether the point is finite) is public.
pub type @XY@(F) = { F x; F y; Bool ok; };

@needs(@BW@(F, B))
pub @T@(F) @X@_inf() {
    F z = @X@w_lift(0);
    F one = @X@w_lift(@X@_one());
    return @T@ {.x = z, .y = one, .z = z};
}
@needs(@BW@(F, B))
pub @T@(F) @X@_gen() {
    F x = @X@w_lift(@X@_gxm());
    F y = @X@w_lift(@X@_gym());
    F one = @X@w_lift(@X@_one());
    return @T@ {.x = x, .y = y, .z = one};
}

// A public affine point entering the computation.
@needs(@BW@(F, B))
pub @T@(F) @X@_from_aff(@A@ a) {
    F x = @X@w_lift(a.x);
    F y = @X@w_lift(a.y);
    F one = @X@w_lift(@X@_one());
    return @T@ {.x = @X@_fto(x), .y = @X@_fto(y), .z = one};
}

// RCB16 algorithm 4: complete addition, a = -3.
@needs(@BW@(F, B))
pub @T@(F) @X@_add(@T@(F) p, @T@(F) q) {
    F b = @X@w_lift(@X@_bm());
    F t0 = @X@_fmul(p.x, q.x);
    F t1 = @X@_fmul(p.y, q.y);
    F t2 = @X@_fmul(p.z, q.z);
    F t3a = @X@_fmul(@X@_fadd(p.x, p.y), @X@_fadd(q.x, q.y));
    F t3 = @X@_fsub(t3a, @X@_fadd(t0, t1));
    F t4a = @X@_fmul(@X@_fadd(p.y, p.z), @X@_fadd(q.y, q.z));
    F t4 = @X@_fsub(t4a, @X@_fadd(t1, t2));
    F x3a = @X@_fmul(@X@_fadd(p.x, p.z), @X@_fadd(q.x, q.z));
    F y3a = @X@_fsub(x3a, @X@_fadd(t0, t2));
    F x3b = @X@_fsub(y3a, @X@_fmul(b, t2));
    F x3c = @X@_fadd(x3b, @X@_fadd(x3b, x3b));
    F z3a = @X@_fsub(t1, x3c);
    F x3d = @X@_fadd(t1, x3c);
    F t2b = @X@_fadd(t2, @X@_fadd(t2, t2));
    F y3b = @X@_fsub(@X@_fsub(@X@_fmul(b, y3a), t2b), t0);
    F y3c = @X@_fadd(y3b, @X@_fadd(y3b, y3b));
    F t0b = @X@_fsub(@X@_fadd(t0, @X@_fadd(t0, t0)), t2b);
    F x3 = @X@_fsub(@X@_fmul(t3, x3d), @X@_fmul(t4, y3c));
    F y3 = @X@_fadd(@X@_fmul(x3d, z3a), @X@_fmul(t0b, y3c));
    F z3 = @X@_fadd(@X@_fmul(t4, z3a), @X@_fmul(t3, t0b));
    return @T@ {.x = x3, .y = y3, .z = z3};
}

// RCB16 algorithm 6: doubling, a = -3.
@needs(@BW@(F, B))
pub @T@(F) @X@_dbl(@T@(F) p) {
    F b = @X@w_lift(@X@_bm());
    F t0 = @X@_fsq(p.x);
    F t1 = @X@_fsq(p.y);
    F t2 = @X@_fsq(p.z);
    F t3a = @X@_fmul(p.x, p.y);
    F t3 = @X@_fadd(t3a, t3a);
    F z3a = @X@_fmul(p.x, p.z);
    F z3b = @X@_fadd(z3a, z3a);
    F y3a = @X@_fsub(@X@_fmul(b, t2), z3b);
    F y3b = @X@_fadd(y3a, @X@_fadd(y3a, y3a));
    F x3a = @X@_fsub(t1, y3b);
    F y3c = @X@_fmul(x3a, @X@_fadd(t1, y3b));
    F x3b = @X@_fmul(x3a, t3);
    F t2b = @X@_fadd(t2, @X@_fadd(t2, t2));
    F z3c = @X@_fsub(@X@_fsub(@X@_fmul(b, z3b), t2b), t0);
    F z3d = @X@_fadd(z3c, @X@_fadd(z3c, z3c));
    F t0b = @X@_fsub(@X@_fadd(t0, @X@_fadd(t0, t0)), t2b);
    F y3 = @X@_fadd(y3c, @X@_fmul(t0b, z3d));
    F t0c = @X@_fmul(p.y, p.z);
    F t0d = @X@_fadd(t0c, t0c);
    F x3 = @X@_fsub(x3b, @X@_fmul(t0d, z3d));
    F z3e = @X@_fmul(t0d, t1);
    F z3f = @X@_fadd(z3e, z3e);
    return @T@ {.x = x3, .y = y3, .z = @X@_fadd(z3f, z3f)};
}

// a when mask is all ones, b when it is zero.
@needs(@BW@(F, B))
@T@(F) @X@_sel(F mask, @T@(F) a, @T@(F) b) {
    F ones = @X@w_lift(@X@_ones());
    F nm = @X@w_xor(mask, ones);
    return @T@ {.x = @X@w_or(@X@w_and(a.x, mask), @X@w_and(b.x, nm)), .y = @X@w_or(@X@w_and(a.y, mask), @X@w_and(b.y, nm)), .z = @X@w_or(@X@w_and(a.z, mask), @X@w_and(b.z, nm))};
}

@needs(@BW@(F, B))
@T@(F) @X@_ladder(F k, Int i, @T@(F) r, @T@(F) p) {
    if (i < 0) { return r; }
    @T@(F) d = @X@_dbl(r);
    return @X@_ladder(k, i - 1, @X@_sel(@X@w_mask(@X@w_shr(k, i)), @X@_add(d, p), d), p);
}

// k * p for k < 2^@K@: every bit costs one doubling and one addition.
@needs(@BW@(F, B))
pub @T@(F) @X@_mul(F k, @T@(F) p) {
    @T@(F) z = @X@_inf();
    return @X@_ladder(k, @KM1@, z, p);
}

// Back to affine coordinates (no longer Montgomery form). Whether the
// point is infinity is made public here: every caller rejects it.
@needs(@BW@(F, B))
pub @XY@(F) @X@_affine(@T@(F) p) {
    F zi = @X@_finv(p.z);
    UInt(@W@) nz = @X@w_open(@X@_nonzero(p.z));
    return @XY@ {.x = @X@_ffrom(@X@_fmul(p.x, zi)), .y = @X@_ffrom(@X@_fmul(p.y, zi)), .ok = nz == 1};
}

// ─── Encoding ────────────────────────────────────────────────────────

@needs(@BW@(F, B))
F @X@_be_acc(List(B) b, Int i, F acc) {
    if (i >= b.len()) { return acc; }
    return @X@_be_acc(b, i + 1, @X@w_or(@X@w_shl(acc, 8), @X@w_from_byte(b[i])));
}

// A big-endian unsigned integer of at most @KB@ bytes, public or secret
// (more is refused by every caller before it gets here: this keeps only
// the low bits).
@needs(@BW@(F, B))
pub F @X@_load(List(B) b) {
    Int skip = if (b.len() > @KB@) { b.len() - @KB@ } else { 0 };
    F z = @X@w_lift(0);
    return @X@_be_acc(b[skip..], 0, z);
}

pub UInt(@W@) @X@_from_be(List(Int) b) {
    UInt(@W@) v = @X@_load(b);
    return v;
}

@needs(@BW@(F, B))
ListBuf(B) @X@_be_out(F v, Int j, ListBuf(B) acc) {
    if (j >= @KB@) { return acc; }
    return @X@_be_out(v, j + 1, acc.push(@X@w_byte(v, 8 * (@KB@ - 1 - j))));
}

// v as exactly @KB@ big-endian bytes, public or secret.
@needs(@BW@(F, B))
pub List(B) @X@_store(F v) {
    ListBuf(B) acc = ListBuf();
    return @X@_be_out(v, 0, acc).finish();
}

pub List(Int) @X@_to_be(UInt(@W@) v) {
    List(Int) b = @X@_store(v);
    return b;
}

// Whether x, y < p is a point of the curve (ordinary integers).
pub Bool @X@_on_curve(UInt(@W@) x, UInt(@W@) y) {
    if (x >= @X@_p() || y >= @X@_p()) { return false; }
    UInt(@W@) xm = @X@_fto(x);
    UInt(@W@) ym = @X@_fto(y);
    UInt(@W@) x3 = @X@_fmul(@X@_fsq(xm), xm);
    UInt(@W@) rhs = @X@_fadd(@X@_fsub(x3, @X@_fadd(xm, @X@_fadd(xm, xm))), @X@_bm());
    return @X@_fsq(ym) == rhs;
}

pub @A@ @X@_bad() { return @A@ {.x = 0, .y = 0, .ok = false}; }

// SEC 1 §2.3.4: 04 || X || Y, or 02/03 || X (compressed). Anything else,
// a coordinate >= p, or a point off the curve is refused (ok = false).
// There is no encoding of infinity: 00 is refused too.
pub @A@ @X@_decode(List(Int) b) {
    if (b.len() == 1 + 2 * @KB@ && b[0] == 4) {
        UInt(@W@) x = @X@_from_be(b[1..1 + @KB@]);
        UInt(@W@) y = @X@_from_be(b[1 + @KB@..]);
        if (!@X@_on_curve(x, y)) { return @X@_bad(); }
        return @A@ {.x = x, .y = y, .ok = true};
    }
    if (b.len() == 1 + @KB@ && (b[0] == 2 || b[0] == 3)) {
        UInt(@W@) x = @X@_from_be(b[1..]);
        if (x >= @X@_p()) { return @X@_bad(); }
        UInt(@W@) xm = @X@_fto(x);
        UInt(@W@) x3 = @X@_fmul(@X@_fsq(xm), xm);
        UInt(@W@) y2 = @X@_fadd(@X@_fsub(x3, @X@_fadd(xm, @X@_fadd(xm, xm))), @X@_bm());
        UInt(@W@) ym = @X@_fsqrt(y2);
        if (@X@_fsq(ym) != y2) { return @X@_bad(); }
        UInt(@W@) y0 = @X@_ffrom(ym);
        Bool flip = wrapping_i64(y0 & 1) != (b[0] & 1);
        UInt(@W@) y = if (flip) { @X@_csub(wrapping_usub(@X@_p(), y0), @X@_p()) } else { y0 };
        return @A@ {.x = x, .y = y, .ok = true};
    }
    return @X@_bad();
}

// 04 || X || Y.
pub List(Int) @X@_encode(@A@ a) { return [4].concat(@X@_to_be(a.x)).concat(@X@_to_be(a.y)); }

// ─── Keys ────────────────────────────────────────────────────────────

// Whether d is a usable private scalar, 1 <= d < n. The answer is made
// public: a caller rejects a bad key and that is not a secret.
@needs(@BW@(F, B))
pub Bool @X@_scalar_ok(F d) {
    F n = @X@w_lift(@X@_n());
    F one = @X@w_lift(1);
    F below = @X@w_and(@X@w_shr(@X@w_sub(d, n), @WM1@), one);
    return @X@w_open(@X@w_and(below, @X@_nonzero(d))) == 1;
}

// d * G as a public affine point (ok = false when d is not a usable
// scalar). Publishing it is the point of a public key.
@needs(@BW@(F, B))
pub @A@ @X@_public(F d) {
    if (!@X@_scalar_ok(d)) { return @X@_bad(); }
    @T@(F) g = @X@_gen();
    @XY@(F) a = @X@_affine(@X@_mul(d, g));
    return @A@ {.x = @X@w_open(a.x), .y = @X@w_open(a.y), .ok = a.ok};
}

// The x-coordinate of d * Q (SEC 1 §3.3.1), @KB@ bytes, secret when d is;
// empty when d is unusable, Q is not a valid point, or the product is
// infinity.
@needs(@BW@(F, B))
pub List(B) @X@_ecdh(F d, @A@ q) {
    ListBuf(B) eb = ListBuf();
    List(B) none = eb.finish();
    if (!q.ok || !@X@_on_curve(q.x, q.y) || !@X@_scalar_ok(d)) { return none; }
    @T@(F) qp = @X@_from_aff(q);
    @XY@(F) s = @X@_affine(@X@_mul(d, qp));
    if (!s.ok) { return none; }
    return @X@_store(s.x);
}

// ─── ECDSA (SEC 1 §4.1, FIPS 186-5) ─────────────────────────────────

pub type @S@ = { Bool ok; UInt(@W@) r; UInt(@W@) s; };

// The leftmost @K@ bits of a digest as an integer mod n (SEC 1 §4.1.3
// step 5; n has exactly @K@ bits).
pub UInt(@W@) @X@_bits2int(List(Int) digest) {
    List(Int) lead = if (digest.len() > @KB@) { digest[0..@KB@] } else { digest };
    return @X@_reduce_n(@X@_from_be(lead));
}

// Verify (r, s) over a message digest under the public point q. Every
// input is public: this runs on the public copy only.
pub Bool @X@_verify_digest(List(Int) digest, UInt(@W@) r, UInt(@W@) s, @A@ q) {
    if (!q.ok || !@X@_on_curve(q.x, q.y)) { return false; }
    if (r == 0 || s == 0 || r >= @X@_n() || s >= @X@_n()) { return false; }
    UInt(@W@) w = @X@_sinv(@X@_sto(s));
    UInt(@W@) u1 = @X@_sfrom(@X@_smul(@X@_sto(@X@_bits2int(digest)), w));
    UInt(@W@) u2 = @X@_sfrom(@X@_smul(@X@_sto(r), w));
    @T@(UInt(@W@)) g = @X@_gen();
    @T@(UInt(@W@)) qp = @X@_from_aff(q);
    @XY@(UInt(@W@)) pt = @X@_affine(@X@_add(@X@_mul(u1, g), @X@_mul(u2, qp)));
    if (!pt.ok) { return false; }
    return @X@_reduce_n(pt.x) == r;
}

pub @S@ @X@_sig_bad() { return @S@ {.ok = false, .r = 0, .s = 0}; }

// Sign a digest with private scalar d and nonce k (both secret at secret
// types). r and s are published (@X@w_open), and so is whether d and k
// are usable. A k or d outside [1, n-1], or an r or s of zero, gives
// ok = false: the caller draws another nonce. Prefer @X@_sign_digest,
// whose nonce is RFC 6979's.
@needs(@BW@(F, B))
pub @S@ @X@_sign_k(F d, List(Int) digest, F k) {
    if (!@X@_scalar_ok(d) || !@X@_scalar_ok(k)) { return @X@_sig_bad(); }
    @T@(F) g = @X@_gen();
    @XY@(F) rp = @X@_affine(@X@_mul(k, g));
    UInt(@W@) r = @X@w_open(@X@_reduce_n(rp.x));
    F e0 = @X@w_lift(@X@_bits2int(digest));
    F rr = @X@w_lift(r);
    F e = @X@_sto(e0);
    F rd = @X@_smul(@X@_sto(rr), @X@_sto(d));
    UInt(@W@) s = @X@w_open(@X@_sfrom(@X@_smul(@X@_sinv(@X@_sto(k)), @X@_sadd(e, rd))));
    if (!rp.ok || r == 0 || s == 0) { return @X@_sig_bad(); }
    return @S@ {.ok = true, .r = r, .s = s};
}

// ─── RFC 6979 deterministic nonce ────────────────────────────────────
// HMAC-DRBG keyed by the private key: generic HMAC over B (lib/sha256g,
// lib/sha512g), so at secret types the key, every V and K, and the nonce
// stay secret. Only whether a candidate nonce is usable is published.

List(Int) @X@_fill(Int v, Int n, ListBuf(Int) acc) {
    if (n <= 0) { return acc.finish(); }
    return @X@_fill(v, n - 1, acc.push(v));
}

@needs(Word(W, B))
List(B) @X@_lift(List(Int) bs) {
    ListBuf(B) acc = ListBuf();
    return w_lift_bytes(bs, 0, acc);
}

// HMAC with the hash h (SHA-256, SHA-384 or SHA-512; SHA-1 is refused
// before it gets here).
@needs(Word(W, B), Word64(D, B))
List(B) @X@_hmac(HashAlg h, List(B) key, List(B) msg) {
    return match h {
        Sha384 => hmac384g(key, msg),
        Sha512 => hmac512g(key, msg),
        _ => hmac256g(key, msg),
    };
}

// T = V1 || V2 || ... until it has @KB@ bytes (RFC 6979 §3.2 h.2).
@needs(Word(W, B), Word64(D, B))
List(B) @X@_drbg_t(HashAlg h, List(B) kk, List(B) v, List(B) t) {
    if (t.len() >= @KB@) { return t; }
    List(B) v2 = @X@_hmac(h, kk, v);
    return @X@_drbg_t(h, kk, v2, t.concat(v2));
}

@needs(@BW@(F, B), Word(W, B), Word64(D, B))
F @X@_drbg_k(HashAlg h, List(B) kk, List(B) v, Int tries) {
    List(B) t = @X@_drbg_t(h, kk, v, v[0..0]);
    F k = @X@_load(t[0..@KB@]);
    if (@X@_scalar_ok(k) || tries > 64) { return k; }
    // T is whole HMAC blocks, so its last block is the V drawn last (h.3).
    List(B) vlast = t[t.len() - hash_len(h)..];
    List(B) zero = @X@_lift([0]);
    List(B) kk2 = @X@_hmac(h, kk, vlast.concat(zero));
    return @X@_drbg_k(h, kk2, @X@_hmac(h, kk2, vlast), tries + 1);
}

// The RFC 6979 nonce for private key d and a digest made with h.
@needs(@BW@(F, B), Word(W, B), Word64(D, B))
pub F @X@_rfc6979_k(HashAlg h, F d, List(Int) digest) {
    Int hl = hash_len(h);
    List(B) bx = @X@_store(d);
    List(B) bh = @X@_lift(@X@_to_be(@X@_bits2int(digest)));
    List(B) v0 = @X@_lift(@X@_fill(1, hl, ListBuf()));
    List(B) k0 = @X@_lift(@X@_fill(0, hl, ListBuf()));
    List(B) b0 = @X@_lift([0]);
    List(B) b1 = @X@_lift([1]);
    List(B) k1 = @X@_hmac(h, k0, v0.concat(b0).concat(bx).concat(bh));
    List(B) v1 = @X@_hmac(h, k1, v0);
    List(B) k2 = @X@_hmac(h, k1, v1.concat(b1).concat(bx).concat(bh));
    List(B) v2 = @X@_hmac(h, k2, v1);
    return @X@_drbg_k(h, k2, v2, 0);
}

// Sign a digest made with h, nonce from RFC 6979. SHA-1 is refused
// (ok = false): no signature this library makes uses it.
@needs(@BW@(F, B), Word(W, B), Word64(D, B))
pub @S@ @X@_sign_digest(HashAlg h, F d, List(Int) digest) {
    Bool sha1 = match h { Sha1 => true, _ => false };
    if (sha1) { return @X@_sig_bad(); }
    F k = @X@_rfc6979_k(h, d, digest);
    return @X@_sign_k(d, digest, k);
}
'''


def mod_inv(a, m):
    return pow(a, -1, m)


def render(x, c):
    K, W = c["K"], c["W"]
    p, n = c["p"], c["n"]
    R = 2 ** K
    assert p % 4 == 3 and K % 8 == 0 and n.bit_length() == K
    # t + q*m < 2^(2K+1) and the guard bit K+8 must fit below the top bit.
    assert 2 * K + 2 < W and W % 64 == 0
    vals = {
        "@X@": x, "@T@": c["T"], "@A@": c["A"], "@S@": c["S"], "@NAME@": c["name"],
        "@BW@": c["BW"], "@XY@": c["XY"],
        "@W@": str(W), "@K@": str(K), "@KB@": str(K // 8), "@KM1@": str(K - 1),
        "@K8@": str(K + 8), "@WM1@": str(W - 1),
        "@P@": str(p), "@N@": str(n), "@GX@": str(c["gx"]), "@GY@": str(c["gy"]),
        "@PINV@": str((-mod_inv(p, R)) % R), "@NINV@": str((-mod_inv(n, R)) % R),
        "@RRP@": str(R * R % p), "@RRN@": str(R * R % n),
        "@ONEM@": str(R % p), "@BM@": str(c["b"] * R % p),
        "@GXM@": str(c["gx"] * R % p), "@GYM@": str(c["gy"] * R % p),
        "@PM2@": str(p - 2), "@NM2@": str(n - 2), "@PSQ@": str((p + 1) // 4),
        "@RMASK@": str(R - 1), "@GUARD@": str(2 ** (K + 8)), "@GMASK@": str(2 ** (K + 8) - 1),
        "@ONES@": str(2 ** W - 1),
    }
    out = TEMPLATE
    # longest tokens first so @K@ does not eat @KB@ etc.
    for k in sorted(vals, key=len, reverse=True):
        out = out.replace(k, vals[k])
    assert not re.search(r"@[A-Z0-9]+@", out), "unreplaced token"
    return out


def main():
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    for x, c in CURVES.items():
        path = os.path.join(root, "lib", x + ".resid")
        with open(path, "w") as f:
            f.write(render(x, c))
        print("wrote", os.path.relpath(path, root))


if __name__ == "__main__":
    main()
