#!/usr/bin/env python3
"""Generate lib/p256.resid and lib/p384.resid from one template.

Both curves share every line of their arithmetic; only the width, the
prime, the order and the constants differ. Edit the template here and
rerun (python3 tools/gen_nistp.py); never edit the generated files.

Design (see the header written into each file):
  - field and scalar elements are native UInt(W) integers in Montgomery
    form, with R = 2^K and W wide enough that t + q*m never overflows;
  - every operation on a secret is branch-free (masks, no comparisons,
    no data-dependent indexing) and uses wrapping_u* so no overflow check
    branches on a secret either;
  - points use the complete projective formulas of Renes, Costello and
    Batina (2016, algorithms 4 and 6, a = -3), so infinity and doubling
    need no special case, and scalar multiplication is a fixed-length
    double-and-add-always with a masked select.
"""
import os

CURVES = {
    "p256": dict(
        K=256, W=576, T="P256Pt", A="P256Aff", S="P256Sig",
        p=2**256 - 2**224 + 2**192 + 2**96 - 1,
        n=0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551,
        b=0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b,
        gx=0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296,
        gy=0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5,
        name="NIST P-256 (secp256r1)",
    ),
    "p384": dict(
        K=384, W=832, T="P384Pt", A="P384Aff", S="P384Sig",
        p=2**384 - 2**128 - 2**96 + 2**32 - 1,
        n=0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973,
        b=0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef,
        gx=0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7,
        gy=0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f,
        name="NIST P-384 (secp384r1)",
    ),
}

TEMPLATE = r'''// lib/@X@.resid — @NAME@: ECDSA (verify, sign with an RFC 6979
// deterministic nonce), ECDH and point decoding, in pure Resid.
//
// GENERATED by tools/gen_nistp.py from the template shared with the other
// NIST curve; edit the generator, not this file.
//
// Field and scalar elements are UInt(@W@) values in Montgomery form
// (R = 2^@K@). @W@ bits leave room for t + q*m, so nothing wraps. Every
// operation that can see a secret (a private key, a nonce, an ECDH
// result) is branch-free: selects are masks, reductions subtract with a
// borrow bit, the scalar ladder runs all @K@ steps, and arithmetic is
// wrapping_u* so no overflow check branches on a secret either. The
// places where a secret-derived fact is deliberately made public (a
// rejected nonce, a result at infinity) go through ct_public, so
// tests/ct can check the rest under valgrind.
//
// Points are projective (X:Y:Z) with the complete formulas of Renes,
// Costello and Batina (2016, algorithms 4 and 6 for a = -3): one formula
// covers doubling and the point at infinity (Z = 0), so there is no
// special case to branch on.

import "hash.resid";

// ─── Constants ───────────────────────────────────────────────────────

pub Int @X@_bytes() { return @KB@; }
pub UInt(@W@) @X@_p() { return @P@; }
pub UInt(@W@) @X@_n() { return @N@; }
pub UInt(@W@) @X@_gx() { return @GX@; }
pub UInt(@W@) @X@_gy() { return @GY@; }
// -p^-1 and -n^-1 mod R
UInt(@W@) @X@_pinv() { return @PINV@; }
UInt(@W@) @X@_ninv() { return @NINV@; }
// R^2 mod p and R^2 mod n, to enter the Montgomery domain
UInt(@W@) @X@_rrp() { return @RRP@; }
UInt(@W@) @X@_rrn() { return @RRN@; }
// R mod p (one), b and G, all in Montgomery form
UInt(@W@) @X@_one() { return @ONEM@; }
UInt(@W@) @X@_bm() { return @BM@; }
UInt(@W@) @X@_gxm() { return @GXM@; }
UInt(@W@) @X@_gym() { return @GYM@; }
// p - 2, n - 2 (inversion) and (p + 1) / 4 (square root; p = 3 mod 4)
UInt(@W@) @X@_pm2() { return @PM2@; }
UInt(@W@) @X@_nm2() { return @NM2@; }
UInt(@W@) @X@_psq() { return @PSQ@; }
// R - 1, the guard bit 2^(K+8) and the mask below it, all ones
UInt(@W@) @X@_rmask() { return @RMASK@; }
UInt(@W@) @X@_guard() { return @GUARD@; }
UInt(@W@) @X@_gmask() { return @GMASK@; }
UInt(@W@) @X@_ones() { return @ONES@; }
UInt(@W@) @X@_zero() { return 0; }

// ─── Branch-free helpers ─────────────────────────────────────────────

// All ones when bit (0 or 1) is 1, else zero. The bit passes through
// ct_hide so the optimizer cannot turn the mask back into a branch.
UInt(@W@) @X@_mask(UInt(@W@) bit) {
    Int h = ct_hide(wrapping_i64(bit & 1));
    return wrapping_usub(@X@_zero(), (UInt(@W@)) wrapping_u64(h));
}

// 1 when v != 0, else 0 (v < 2^(@W@-1)): 0 - v has its top bit set
// exactly when v is nonzero.
pub UInt(@W@) @X@_nonzero(UInt(@W@) v) {
    return ((v | wrapping_usub(@X@_zero(), v)) >> @WM1@) & 1;
}

// u - m when u >= m, else u, for u < 2m.
UInt(@W@) @X@_csub(UInt(@W@) u, UInt(@W@) m) {
    UInt(@W@) d = wrapping_usub(wrapping_uadd(u, @X@_guard()), m);
    UInt(@W@) keep = @X@_mask((d >> @K8@) & 1);
    return ((d & @X@_gmask()) & keep) | (u & (keep ^ @X@_ones()));
}

// a * b / R mod m (Montgomery), a, b < m.
UInt(@W@) @X@_mont(UInt(@W@) a, UInt(@W@) b, UInt(@W@) m, UInt(@W@) minv) {
    UInt(@W@) t = wrapping_umul(a, b);
    UInt(@W@) q = wrapping_umul(t & @X@_rmask(), minv) & @X@_rmask();
    return @X@_csub(wrapping_uadd(t, wrapping_umul(q, m)) >> @K@, m);
}

// ─── Field (mod p), Montgomery form ──────────────────────────────────

pub UInt(@W@) @X@_fmul(UInt(@W@) a, UInt(@W@) b) { return @X@_mont(a, b, @X@_p(), @X@_pinv()); }
pub UInt(@W@) @X@_fsq(UInt(@W@) a) { return @X@_mont(a, a, @X@_p(), @X@_pinv()); }
pub UInt(@W@) @X@_fadd(UInt(@W@) a, UInt(@W@) b) { return @X@_csub(wrapping_uadd(a, b), @X@_p()); }
pub UInt(@W@) @X@_fsub(UInt(@W@) a, UInt(@W@) b) { return @X@_csub(wrapping_usub(wrapping_uadd(a, @X@_p()), b), @X@_p()); }
pub UInt(@W@) @X@_fto(UInt(@W@) a) { return @X@_fmul(a, @X@_rrp()); }
pub UInt(@W@) @X@_ffrom(UInt(@W@) a) { return @X@_fmul(a, 1); }

// a^e for a public exponent e, MSB first from bit i.
UInt(@W@) @X@_fpow(UInt(@W@) a, UInt(@W@) e, Int i, UInt(@W@) acc) {
    if (i < 0) { return acc; }
    UInt(@W@) s = @X@_fsq(acc);
    UInt(@W@) sh = (UInt(@W@)) i;
    UInt(@W@) r = if (((e >> sh) & 1) == 1) { @X@_fmul(s, a) } else { s };
    return @X@_fpow(a, e, i - 1, r);
}

// 1/a (Fermat); 0 maps to 0.
pub UInt(@W@) @X@_finv(UInt(@W@) a) { return @X@_fpow(a, @X@_pm2(), @KM1@, @X@_one()); }

// A square root of a when one exists (check by squaring).
pub UInt(@W@) @X@_fsqrt(UInt(@W@) a) { return @X@_fpow(a, @X@_psq(), @KM1@, @X@_one()); }

// ─── Scalars (mod n), Montgomery form ────────────────────────────────

pub UInt(@W@) @X@_smul(UInt(@W@) a, UInt(@W@) b) { return @X@_mont(a, b, @X@_n(), @X@_ninv()); }
pub UInt(@W@) @X@_sadd(UInt(@W@) a, UInt(@W@) b) { return @X@_csub(wrapping_uadd(a, b), @X@_n()); }
pub UInt(@W@) @X@_sto(UInt(@W@) a) { return @X@_smul(a, @X@_rrn()); }
pub UInt(@W@) @X@_sfrom(UInt(@W@) a) { return @X@_smul(a, 1); }

UInt(@W@) @X@_spow(UInt(@W@) a, UInt(@W@) e, Int i, UInt(@W@) acc) {
    if (i < 0) { return acc; }
    UInt(@W@) s = @X@_smul(acc, acc);
    UInt(@W@) sh = (UInt(@W@)) i;
    UInt(@W@) r = if (((e >> sh) & 1) == 1) { @X@_smul(s, a) } else { s };
    return @X@_spow(a, e, i - 1, r);
}

// 1/a mod n, both in Montgomery form.
pub UInt(@W@) @X@_sinv(UInt(@W@) a) { return @X@_spow(a, @X@_nm2(), @KM1@, @X@_sto(1)); }

// A value below 2^@K@ reduced mod n (2^@K@ < 2n).
pub UInt(@W@) @X@_reduce_n(UInt(@W@) v) { return @X@_csub(v, @X@_n()); }

// ─── Points ──────────────────────────────────────────────────────────

// Projective, Montgomery-form coordinates; Z = 0 is infinity.
pub type @T@ = { UInt(@W@) x; UInt(@W@) y; UInt(@W@) z; };

// Affine, ordinary integers; ok is false for infinity or a bad encoding.
pub type @A@ = { UInt(@W@) x; UInt(@W@) y; Bool ok; };

pub @T@ @X@_inf() { return @T@ {.x = 0, .y = @X@_one(), .z = 0}; }
pub @T@ @X@_gen() { return @T@ {.x = @X@_gxm(), .y = @X@_gym(), .z = @X@_one()}; }

pub @T@ @X@_from_aff(@A@ a) {
    return @T@ {.x = @X@_fto(a.x), .y = @X@_fto(a.y), .z = @X@_one()};
}

// RCB16 algorithm 4: complete addition, a = -3.
pub @T@ @X@_add(@T@ p, @T@ q) {
    UInt(@W@) b = @X@_bm();
    UInt(@W@) t0 = @X@_fmul(p.x, q.x);
    UInt(@W@) t1 = @X@_fmul(p.y, q.y);
    UInt(@W@) t2 = @X@_fmul(p.z, q.z);
    UInt(@W@) t3a = @X@_fmul(@X@_fadd(p.x, p.y), @X@_fadd(q.x, q.y));
    UInt(@W@) t3 = @X@_fsub(t3a, @X@_fadd(t0, t1));
    UInt(@W@) t4a = @X@_fmul(@X@_fadd(p.y, p.z), @X@_fadd(q.y, q.z));
    UInt(@W@) t4 = @X@_fsub(t4a, @X@_fadd(t1, t2));
    UInt(@W@) x3a = @X@_fmul(@X@_fadd(p.x, p.z), @X@_fadd(q.x, q.z));
    UInt(@W@) y3a = @X@_fsub(x3a, @X@_fadd(t0, t2));
    UInt(@W@) x3b = @X@_fsub(y3a, @X@_fmul(b, t2));
    UInt(@W@) x3c = @X@_fadd(x3b, @X@_fadd(x3b, x3b));
    UInt(@W@) z3a = @X@_fsub(t1, x3c);
    UInt(@W@) x3d = @X@_fadd(t1, x3c);
    UInt(@W@) t2b = @X@_fadd(t2, @X@_fadd(t2, t2));
    UInt(@W@) y3b = @X@_fsub(@X@_fsub(@X@_fmul(b, y3a), t2b), t0);
    UInt(@W@) y3c = @X@_fadd(y3b, @X@_fadd(y3b, y3b));
    UInt(@W@) t0b = @X@_fsub(@X@_fadd(t0, @X@_fadd(t0, t0)), t2b);
    UInt(@W@) x3 = @X@_fsub(@X@_fmul(t3, x3d), @X@_fmul(t4, y3c));
    UInt(@W@) y3 = @X@_fadd(@X@_fmul(x3d, z3a), @X@_fmul(t0b, y3c));
    UInt(@W@) z3 = @X@_fadd(@X@_fmul(t4, z3a), @X@_fmul(t3, t0b));
    return @T@ {.x = x3, .y = y3, .z = z3};
}

// RCB16 algorithm 6: doubling, a = -3.
pub @T@ @X@_dbl(@T@ p) {
    UInt(@W@) b = @X@_bm();
    UInt(@W@) t0 = @X@_fsq(p.x);
    UInt(@W@) t1 = @X@_fsq(p.y);
    UInt(@W@) t2 = @X@_fsq(p.z);
    UInt(@W@) t3a = @X@_fmul(p.x, p.y);
    UInt(@W@) t3 = @X@_fadd(t3a, t3a);
    UInt(@W@) z3a = @X@_fmul(p.x, p.z);
    UInt(@W@) z3b = @X@_fadd(z3a, z3a);
    UInt(@W@) y3a = @X@_fsub(@X@_fmul(b, t2), z3b);
    UInt(@W@) y3b = @X@_fadd(y3a, @X@_fadd(y3a, y3a));
    UInt(@W@) x3a = @X@_fsub(t1, y3b);
    UInt(@W@) y3c = @X@_fmul(x3a, @X@_fadd(t1, y3b));
    UInt(@W@) x3b = @X@_fmul(x3a, t3);
    UInt(@W@) t2b = @X@_fadd(t2, @X@_fadd(t2, t2));
    UInt(@W@) z3c = @X@_fsub(@X@_fsub(@X@_fmul(b, z3b), t2b), t0);
    UInt(@W@) z3d = @X@_fadd(z3c, @X@_fadd(z3c, z3c));
    UInt(@W@) t0b = @X@_fsub(@X@_fadd(t0, @X@_fadd(t0, t0)), t2b);
    UInt(@W@) y3 = @X@_fadd(y3c, @X@_fmul(t0b, z3d));
    UInt(@W@) t0c = @X@_fmul(p.y, p.z);
    UInt(@W@) t0d = @X@_fadd(t0c, t0c);
    UInt(@W@) x3 = @X@_fsub(x3b, @X@_fmul(t0d, z3d));
    UInt(@W@) z3e = @X@_fmul(t0d, t1);
    UInt(@W@) z3f = @X@_fadd(z3e, z3e);
    return @T@ {.x = x3, .y = y3, .z = @X@_fadd(z3f, z3f)};
}

// a when mask is all ones, b when it is zero.
@T@ @X@_sel(UInt(@W@) mask, @T@ a, @T@ b) {
    UInt(@W@) nm = mask ^ @X@_ones();
    return @T@ {.x = (a.x & mask) | (b.x & nm), .y = (a.y & mask) | (b.y & nm), .z = (a.z & mask) | (b.z & nm)};
}

@T@ @X@_ladder(UInt(@W@) k, Int i, @T@ r, @T@ p) {
    if (i < 0) { return r; }
    @T@ d = @X@_dbl(r);
    UInt(@W@) sh = (UInt(@W@)) i;
    return @X@_ladder(k, i - 1, @X@_sel(@X@_mask((k >> sh) & 1), @X@_add(d, p), d), p);
}

// k * p for k < 2^@K@: every bit costs one doubling and one addition.
pub @T@ @X@_mul(UInt(@W@) k, @T@ p) { return @X@_ladder(k, @KM1@, @X@_inf(), p); }

// Back to affine ordinary integers. Whether the point is infinity is
// made public here: every caller rejects it.
pub @A@ @X@_affine(@T@ p) {
    UInt(@W@) zi = @X@_finv(p.z);
    Int nz = ct_public(wrapping_i64(@X@_nonzero(p.z)));
    return @A@ {.x = @X@_ffrom(@X@_fmul(p.x, zi)), .y = @X@_ffrom(@X@_fmul(p.y, zi)), .ok = nz == 1};
}

// ─── Encoding ────────────────────────────────────────────────────────

UInt(@W@) @X@_be_acc(List(Int) b, Int i, UInt(@W@) acc) {
    if (i >= b.len()) { return acc; }
    UInt(@W@) byte = (UInt(@W@)) wrapping_u64(b[i] & 255);
    return @X@_be_acc(b, i + 1, (acc << 8) | byte);
}

// A big-endian unsigned integer of at most @KB@ bytes (more is refused
// by every caller before it gets here: this keeps only the low bits).
pub UInt(@W@) @X@_from_be(List(Int) b) {
    Int skip = if (b.len() > @KB@) { b.len() - @KB@ } else { 0 };
    return @X@_be_acc(b[skip..], 0, 0);
}

ListBuf(Int) @X@_be_out(UInt(@W@) v, Int j, ListBuf(Int) acc) {
    if (j >= @KB@) { return acc; }
    UInt(@W@) sh = (UInt(@W@)) (8 * (@KB@ - 1 - j));
    return @X@_be_out(v, j + 1, acc.push(wrapping_i64((v >> sh) & 255)));
}

// v as exactly @KB@ big-endian bytes.
pub List(Int) @X@_to_be(UInt(@W@) v) { return @X@_be_out(v, 0, ListBuf()).finish(); }

// Whether x, y < p is a point of the curve (ordinary integers).
pub Bool @X@_on_curve(UInt(@W@) x, UInt(@W@) y) {
    if (x >= @X@_p() || y >= @X@_p()) { return false; }
    UInt(@W@) xm = @X@_fto(x);
    UInt(@W@) ym = @X@_fto(y);
    UInt(@W@) x3 = @X@_fmul(@X@_fsq(xm), xm);
    UInt(@W@) rhs = @X@_fadd(@X@_fsub(x3, @X@_fadd(xm, @X@_fadd(xm, xm))), @X@_bm());
    return @X@_fsq(ym) == rhs;
}

pub @A@ @X@_bad() { return @A@ {.x = 0, .y = 0, .ok = false}; }

// SEC 1 §2.3.4: 04 || X || Y, or 02/03 || X (compressed). Anything else,
// a coordinate >= p, or a point off the curve is refused (ok = false).
// There is no encoding of infinity: 00 is refused too.
pub @A@ @X@_decode(List(Int) b) {
    if (b.len() == 1 + 2 * @KB@ && b[0] == 4) {
        UInt(@W@) x = @X@_from_be(b[1..1 + @KB@]);
        UInt(@W@) y = @X@_from_be(b[1 + @KB@..]);
        if (!@X@_on_curve(x, y)) { return @X@_bad(); }
        return @A@ {.x = x, .y = y, .ok = true};
    }
    if (b.len() == 1 + @KB@ && (b[0] == 2 || b[0] == 3)) {
        UInt(@W@) x = @X@_from_be(b[1..]);
        if (x >= @X@_p()) { return @X@_bad(); }
        UInt(@W@) xm = @X@_fto(x);
        UInt(@W@) x3 = @X@_fmul(@X@_fsq(xm), xm);
        UInt(@W@) y2 = @X@_fadd(@X@_fsub(x3, @X@_fadd(xm, @X@_fadd(xm, xm))), @X@_bm());
        UInt(@W@) ym = @X@_fsqrt(y2);
        if (@X@_fsq(ym) != y2) { return @X@_bad(); }
        UInt(@W@) y0 = @X@_ffrom(ym);
        Bool flip = wrapping_i64(y0 & 1) != (b[0] & 1);
        UInt(@W@) y = if (flip) { @X@_csub(wrapping_usub(@X@_p(), y0), @X@_p()) } else { y0 };
        return @A@ {.x = x, .y = y, .ok = true};
    }
    return @X@_bad();
}

// 04 || X || Y.
pub List(Int) @X@_encode(@A@ a) { return [4].concat(@X@_to_be(a.x)).concat(@X@_to_be(a.y)); }

// ─── Keys ────────────────────────────────────────────────────────────

// Whether d is a usable private scalar, 1 <= d < n. The answer is made
// public: a caller rejects a bad key and that is not a secret.
pub Bool @X@_scalar_ok(UInt(@W@) d) {
    UInt(@W@) below = (wrapping_usub(d, @X@_n()) >> @WM1@) & 1;
    Int ok = ct_public(wrapping_i64(below & @X@_nonzero(d)));
    return ok == 1;
}

// d * G as an affine point (ok = false when d is not a usable scalar).
pub @A@ @X@_public(UInt(@W@) d) {
    if (!@X@_scalar_ok(d)) { return @X@_bad(); }
    @A@ a = @X@_affine(@X@_mul(d, @X@_gen()));
    return @A@ {.x = ct_public(a.x), .y = ct_public(a.y), .ok = a.ok};
}

// The x-coordinate of d * Q (SEC 1 §3.3.1), @KB@ bytes; empty when d is
// unusable, Q is not a valid point, or the product is infinity.
pub List(Int) @X@_ecdh(UInt(@W@) d, @A@ q) {
    if (!q.ok || !@X@_on_curve(q.x, q.y) || !@X@_scalar_ok(d)) { return []; }
    @A@ s = @X@_affine(@X@_mul(d, @X@_from_aff(q)));
    if (!s.ok) { return []; }
    return @X@_to_be(s.x);
}

// ─── ECDSA (SEC 1 §4.1, FIPS 186-5) ─────────────────────────────────

pub type @S@ = { Bool ok; UInt(@W@) r; UInt(@W@) s; };

// The leftmost @K@ bits of a digest as an integer mod n (SEC 1 §4.1.3
// step 5; n has exactly @K@ bits).
pub UInt(@W@) @X@_bits2int(List(Int) digest) {
    List(Int) lead = if (digest.len() > @KB@) { digest[0..@KB@] } else { digest };
    return @X@_reduce_n(@X@_from_be(lead));
}

// Verify (r, s) over a message digest under the public point q.
pub Bool @X@_verify_digest(List(Int) digest, UInt(@W@) r, UInt(@W@) s, @A@ q) {
    if (!q.ok || !@X@_on_curve(q.x, q.y)) { return false; }
    if (r == 0 || s == 0 || r >= @X@_n() || s >= @X@_n()) { return false; }
    UInt(@W@) w = @X@_sinv(@X@_sto(s));
    UInt(@W@) u1 = @X@_sfrom(@X@_smul(@X@_sto(@X@_bits2int(digest)), w));
    UInt(@W@) u2 = @X@_sfrom(@X@_smul(@X@_sto(r), w));
    @A@ pt = @X@_affine(@X@_add(@X@_mul(u1, @X@_gen()), @X@_mul(u2, @X@_from_aff(q))));
    if (!pt.ok) { return false; }
    return @X@_reduce_n(pt.x) == r;
}

pub @S@ @X@_sig_bad() { return @S@ {.ok = false, .r = 0, .s = 0}; }

// Sign a digest with private scalar d and nonce k (both secret). A k or
// d outside [1, n-1], or an r or s of zero, gives ok = false: the caller
// draws another nonce. Prefer @X@_sign_digest, whose nonce is RFC 6979's.
pub @S@ @X@_sign_k(UInt(@W@) d, List(Int) digest, UInt(@W@) k) {
    if (!@X@_scalar_ok(d) || !@X@_scalar_ok(k)) { return @X@_sig_bad(); }
    @A@ rp = @X@_affine(@X@_mul(k, @X@_gen()));
    UInt(@W@) r = ct_public(@X@_reduce_n(rp.x));
    UInt(@W@) e = @X@_sto(@X@_bits2int(digest));
    UInt(@W@) sm = @X@_smul(@X@_sinv(@X@_sto(k)), @X@_sadd(e, @X@_smul(@X@_sto(r), @X@_sto(d))));
    UInt(@W@) s = ct_public(@X@_sfrom(sm));
    if (!rp.ok || r == 0 || s == 0) { return @X@_sig_bad(); }
    return @S@ {.ok = true, .r = r, .s = s};
}

// ─── RFC 6979 deterministic nonce ────────────────────────────────────

List(Int) @X@_fill(Int v, Int n, ListBuf(Int) acc) {
    if (n <= 0) { return acc.finish(); }
    return @X@_fill(v, n - 1, acc.push(v));
}

// T = V1 || V2 || ... until it has @KB@ bytes (RFC 6979 §3.2 h.2).
List(Int) @X@_drbg_t(HashAlg h, List(Int) kk, List(Int) v, List(Int) t) {
    if (t.len() >= @KB@) { return t; }
    List(Int) v2 = hmac_bytes(h, kk, v);
    return @X@_drbg_t(h, kk, v2, t.concat(v2));
}

UInt(@W@) @X@_drbg_k(HashAlg h, List(Int) kk, List(Int) v, Int tries) {
    List(Int) t = @X@_drbg_t(h, kk, v, []);
    UInt(@W@) k = @X@_from_be(t[0..@KB@]);
    if (@X@_scalar_ok(k) || tries > 64) { return k; }
    // T is whole HMAC blocks, so its last block is the V drawn last (h.3).
    List(Int) vlast = t[t.len() - hash_len(h)..];
    List(Int) kk2 = hmac_bytes(h, kk, vlast.concat([0]));
    return @X@_drbg_k(h, kk2, hmac_bytes(h, kk2, vlast), tries + 1);
}

// The RFC 6979 nonce for private key d and a digest made with h.
pub UInt(@W@) @X@_rfc6979_k(HashAlg h, UInt(@W@) d, List(Int) digest) {
    Int hl = hash_len(h);
    List(Int) bx = @X@_to_be(d);
    List(Int) bh = @X@_to_be(@X@_bits2int(digest));
    List(Int) v0 = @X@_fill(1, hl, ListBuf());
    List(Int) k0 = @X@_fill(0, hl, ListBuf());
    List(Int) k1 = hmac_bytes(h, k0, v0.concat([0]).concat(bx).concat(bh));
    List(Int) v1 = hmac_bytes(h, k1, v0);
    List(Int) k2 = hmac_bytes(h, k1, v1.concat([1]).concat(bx).concat(bh));
    List(Int) v2 = hmac_bytes(h, k2, v1);
    return @X@_drbg_k(h, k2, v2, 0);
}

// Sign a digest made with h, nonce from RFC 6979.
pub @S@ @X@_sign_digest(HashAlg h, UInt(@W@) d, List(Int) digest) {
    return @X@_sign_k(d, digest, @X@_rfc6979_k(h, d, digest));
}
'''


def mod_inv(a, m):
    return pow(a, -1, m)


def render(x, c):
    K, W = c["K"], c["W"]
    p, n = c["p"], c["n"]
    R = 2 ** K
    assert p % 4 == 3 and K % 8 == 0 and n.bit_length() == K
    # t + q*m < 2^(2K+1) and the guard bit K+8 must fit below the top bit.
    assert 2 * K + 2 < W and W % 64 == 0
    vals = {
        "@X@": x, "@T@": c["T"], "@A@": c["A"], "@S@": c["S"], "@NAME@": c["name"],
        "@W@": str(W), "@K@": str(K), "@KB@": str(K // 8), "@KM1@": str(K - 1),
        "@K8@": str(K + 8), "@WM1@": str(W - 1),
        "@P@": str(p), "@N@": str(n), "@GX@": str(c["gx"]), "@GY@": str(c["gy"]),
        "@PINV@": str((-mod_inv(p, R)) % R), "@NINV@": str((-mod_inv(n, R)) % R),
        "@RRP@": str(R * R % p), "@RRN@": str(R * R % n),
        "@ONEM@": str(R % p), "@BM@": str(c["b"] * R % p),
        "@GXM@": str(c["gx"] * R % p), "@GYM@": str(c["gy"] * R % p),
        "@PM2@": str(p - 2), "@NM2@": str(n - 2), "@PSQ@": str((p + 1) // 4),
        "@RMASK@": str(R - 1), "@GUARD@": str(2 ** (K + 8)), "@GMASK@": str(2 ** (K + 8) - 1),
        "@ONES@": str(2 ** W - 1),
    }
    out = TEMPLATE
    # longest tokens first so @K@ does not eat @KB@ etc.
    for k in sorted(vals, key=len, reverse=True):
        out = out.replace(k, vals[k])
    assert "@" not in out, "unreplaced token"
    return out


def main():
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    for x, c in CURVES.items():
        path = os.path.join(root, "lib", x + ".resid")
        with open(path, "w") as f:
            f.write(render(x, c))
        print("wrote", os.path.relpath(path, root))


if __name__ == "__main__":
    main()
